version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ratelimiter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node1:
    build: ./backend
    container_name: node1
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ratelimiter
    depends_on:
      - redis
      - postgres

  node2:
    build: ./backend
    container_name: node2
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ratelimiter
    depends_on:
      - redis
      - postgres

  node3:
    build: ./backend
    container_name: node3
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ratelimiter
    depends_on:
      - redis
      - postgres

  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3

volumes:
  postgres_data:
