version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis

  node1:
    build: ./backend
    container_name: node1
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis

  node2:
    build: ./backend
    container_name: node2
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis

  node3:
    build: ./backend
    container_name: node3
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis

  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - loadbalancer
